### PR TITLE
Add basic validation for strategies

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Add some basic validation for strategies. As of now, based on string validation that is shoved into configmap.

/cc @sjenning

### CODE REVIEW

**Comment by sjenning** [comment]
can we add some unit tests?

**Comment by ravisantoshgudimetla** [comment]
Sure, I wanted to have e2es first though. Writing unit tests involve a lot of mocking(especially at the controller level). I will add some unit tests tomorrow for some functions.

**Comment by sjenning** [comment]
seems like it wouldn't be hard to turn the validation code block into a function that only took the strategies as an argument and would be easier to unit test. `Reconcile()` could use some decomposition anyway IMHO.

**Pull request merged**
